Repository proyais/aisalud, pull requests merged in 2021-07, with the labels that each got.

#9 fix: Corrige error al filtrar categorias dentro de una jerarquia
  modules/filtros.R
  widgets/episodios_jerarquia_server.R
Labels: bug

#10 fix: Corrige validación de nota técnica para inclusiones y exclusiones
  json_schemas/nota_tecnica.json
  man/cargar_datos.md
Labels: bug

#12 Release v21.07.2
  .github/ISSUE_TEMPLATE/reportar-un-error.md
  .github/ISSUE_TEMPLATE/solicitud-de-mejora.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  json_schemas/nota_tecnica.json
  man/cargar_datos.md
  modules/filtros.R
  ui.R
  widgets/episodios_jerarquia_server.R
Labels: bug

#14 refactor: Corrige typo en outliers
  modules/filtros.R
  modules/outliers.R
Labels: mejora

#19 Agrega paquete shinyCache
  global.R
  renv.lock
Labels: mejora

#17 refactor: Simplificar funciones largas
  R/caja_de_bigotes_agrupador.R
  R/comparar_nt_valor_factura.R
  R/completar_meses.R
  R/descriptiva_timeseries.R
  R/episodios_jerarquia.R
  R/frecuencias.R
  R/frecuencias_dia.R
  R/frecuencias_jerarquia.R
  R/frecuencias_mes.R
  R/identificar_episodios.R
  widgets/episodios_jerarquia_server.R
Labels: mejora

#21 Reemplaza codigo cache por funcion cache_call
  R/counter.R
  R/pull_distinct.R
  modules/cargar_datos.R
  modules/composicion.R
  modules/descriptiva.R
  modules/filtros.R
  modules/nota_tecnica.R
  modules/otros_graficos.R
  modules/outliers.R
  modules/seguimiento.R
  server.R
  widgets/episodios_jerarquia_server.R
Labels: mejora

#30 Actualiza paquetes en renv.lock y manifest
  manifest.json
  renv.lock
Labels: mejora

#23 Docs: Documenta funciones en R/
  R/caja_de_bigotes_agrupador.R
  R/completar_meses.R
  R/counter.R
  R/dbListNumericFields.R
  R/descriptiva.R
  R/descriptiva_timeseries.R
  R/episodios_jerarquia.R
  R/esquema_nota_tecnica.R
  R/formatAsCurrency.R
  R/formatAsPerc.R
  R/frec_x_cm.R
  R/frecuencias.R
  R/frecuencias_dia.R
  R/frecuencias_jerarquia.R
  R/frecuencias_mes.R
  R/grafico_barras_descriptiva.R
  R/histograma_agrupador.R
  R/histograma_edades.R
  R/identificar_episodios.R
  R/mapa_valores.R
  R/mes_spanish.R
  R/mes_spanish_inv.R
  R/mes_spanish_juntos.R
  R/notin.R
  R/numerize.R
  R/outliers_iqr.R
  R/outliers_percentil.R
  R/parse_nt.R
  R/parse_nt_indice.R
  R/parse_nt_v1_v2.R
  R/pie_chart.R
  R/pull_distinct.R
  R/round0.R
  R/separar_spanish.R
Labels: documentacion

#27 Permite ajusta filtros en panatallas pequeñas
  www/style.css
Labels: bug

#39 Comparación de notas técnicas con techos y pisos
  R/comparacion_frecuencias.R
  R/comparacion_valor_facturado.R
  R/comparar_nt.R
  R/comparar_nt_frecuencias.R
  R/comparar_nt_valor_factura.R
  R/completar_meses.R
  R/frecuencias.R
  R/frecuencias_jerarquia.R
  R/parse_nt.R
  R/pivot_frecuencias.R
  json_schemas/nota_tecnica.json
  modules/descriptiva.R
  modules/nota_tecnica.R
  modules/seguimiento.R
Labels: mejora

#45 Elimina botón de frecuencias en nota tecnica
  modules/nota_tecnica.R
Labels: mejora

#32 Describe conjunto mínimo de datos
  man/conjunto_datos.md
Labels: documentacion

#47 fix: Corrige ortografía en CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentacion

#41 Corrige frecuencia con episodios complejos
  R/completar_meses.R
Labels: bug

#43 Documenta uso de techos y pisos en seguimiento
  man/cargar_datos.md
  man/nota_tecnica.md
  man/seguimiento_contratos.md
Labels: documentacion

#54 Corrige error de seleccion de rango fechas erroneo
  modules/seguimiento.R
Labels: bug

#58 feat: Adiciona esquema json para paquetes
  json_schemas/paquetes.json
Labels: mejora

#56 fix: Corrige error al cambiar tablas en jerarquia
  widgets/episodios_jerarquia_server.R
Labels: bug

#53 Corrige gramática y otrografía en manuales
  man/agrupadores.md
  man/cargar_datos.md
  man/composicion.md
  man/conjunto_datos.md
  man/descriptiva.md
  man/filtros_opciones.md
  man/nota_tecnica.md
  man/otros_graficos.md
  man/outliers.md
  man/seguimiento_contratos.md
  man/seleccion_datos.md
Labels: mejora

#59 Cambios necesarios para release 21.08.1
  CHANGELOG.md
  ui.R
Labels: mejora

#61 fix: Corrige error con la cración de multiples NTs
  modules/nota_tecnica.R
Labels: bug
